services:
  # Caddy reverse proxy service
  caddy:
    image: caddy:2.8-alpine
    container_name: zapgap-caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Mount Caddyfile configuration
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      # Persistent storage for certificates and data
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - zapgap-network
    depends_on:
      server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    environment:
      - CADDY_ADMIN=off
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  agent:
    build:
      context: ./agent
      dockerfile: Dockerfile
    container_name: zapgap-agent
    # Remove external port exposure - only accessible via internal network
    expose:
      - "4111"
    environment:
      - UPSTASH_REDIS_REST_URL=${UPSTASH_REDIS_REST_URL}
      - UPSTASH_REDIS_REST_TOKEN=${UPSTASH_REDIS_REST_TOKEN}
      - UPSTASH_VECTOR_REST_URL=${UPSTASH_VECTOR_REST_URL}
      - UPSTASH_VECTOR_REST_TOKEN=${UPSTASH_VECTOR_REST_TOKEN}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    volumes:
      # Mount source code for development
      - ./agent/src:/app/src
      # Preserve node_modules and .mastra build output in container
      - agent_node_modules:/app/node_modules
      - agent_mastra_output:/app/.mastra
    networks:
      - zapgap-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4111/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: zapgap-server
    # Remove external port exposure - only accessible via Caddy
    expose:
      - "3000"
    environment:
      - MASTRA_AGENT_URL=http://agent:4111
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - CLERK_PUBLISHABLE_KEY=${CLERK_PUBLISHABLE_KEY}
      - SUPABASE_KEY=${SUPABASE_KEY}
    volumes:
      # Mount source code for development
      - ./server/src:/app/src
      - ./server/package.json:/app/package.json
      - ./server/tsconfig.json:/app/tsconfig.json
      # Preserve node_modules in container
      - server_node_modules:/app/node_modules
    networks:
      - zapgap-network
    depends_on:
      agent:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped

networks:
  zapgap-network:
    driver: bridge
    name: zapgap-network

volumes:
  # Caddy persistent storage
  caddy_data:
    name: zapgap-caddy-data
  caddy_config:
    name: zapgap-caddy-config
  # Application volumes
  agent_node_modules:
    name: zapgap-agent-node-modules
  agent_mastra_output:
    name: zapgap-agent-mastra-output
  server_node_modules:
    name: zapgap-server-node-modules
