version: '3.8'

services:
  agent:
    build:
      context: ./agent
      dockerfile: Dockerfile

    container_name: zapgap-agent
    ports:
      - "4111:4111"
    environment:
      - UPSTASH_REDIS_REST_URL=${UPSTASH_REDIS_REST_URL}
      - UPSTASH_REDIS_REST_TOKEN=${UPSTASH_REDIS_REST_TOKEN}
      - UPSTASH_VECTOR_REST_URL=${UPSTASH_VECTOR_REST_URL}
      - UPSTASH_VECTOR_REST_TOKEN=${UPSTASH_VECTOR_REST_TOKEN}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    volumes:
      # Mount source code for development but preserve built artifacts
      - ./agent/src:/app/src
      - ./agent/package.json:/app/package.json
      - ./agent/bun.lock:/app/bun.lock
      - ./agent/tsconfig.json:/app/tsconfig.json
      # Preserve node_modules and .mastra build output in container
      - agent_node_modules:/app/node_modules
      - agent_mastra_output:/app/.mastra
    networks:
      - zapgap-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4111/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: zapgap-server
    ports:
      - "3000:3000"
    environment:
      - MASTRA_AGENT_URL=http://agent:4111
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - CLERK_PUBLISHABLE_KEY=${CLERK_PUBLISHABLE_KEY}
      - SUPABASE_KEY=${SUPABASE_KEY}
    volumes:
      # Mount source code for development
      - ./server/src:/app/src
      - ./server/package.json:/app/package.json
      - ./server/bun.lock:/app/bun.lock
      - ./server/tsconfig.json:/app/tsconfig.json
      # Preserve node_modules in container
      - server_node_modules:/app/node_modules
    networks:
      - zapgap-network
    depends_on:
      agent:
        condition: service_healthy

networks:
  zapgap-network:
    driver: bridge
    name: zapgap-network

volumes:
  agent_node_modules:
    name: zapgap-agent-node-modules
  agent_mastra_output:
    name: zapgap-agent-mastra-output
  server_node_modules:
    name: zapgap-server-node-modules
